### ISSUE TITLE
Warning when compiling the examples

### ISSUE THREAD

**Issue by vidaljuanp** [sparkfun/SparkFun_SGP30_Arduino_Library#2]
### Subject of the issue
Warning when compiling the examples

### Your workbench
* What platform are you using?
MAC OS High Sierra 10.13.6
* What version of the device are you using? Is there a firmware version?
* How is the device wired to your platform?
Arduino uno red board, qwiic shield, I2C cable, 
redboard connectet to mac laptop via USB
* How is everything being powered?
USB cable to laptop
* Are there any additional details that may help us help you?

### Steps to reproduce
Open example Basic Readings on arduino IDE and compile

In file included from SparkFun_SGP30_Arduino_Library-master/examples/Example2_RawSignals/Example2_RawSignals.ino:17:0:
SparkFun_SGP30_Arduino_Library-master/src/SparkFun_SGP30_Arduino_Library.h:144:13: warning: extra qualification 'SGP30::' on member '_CRC8' [-fpermissive]
     uint8_t SGP30::_CRC8(uint16_t twoBytes);
             ^
In file included from SparkFun_SGP30_Arduino_Library-master/src/SparkFun_SGP30_Arduino_Library.cpp:40:0:
SparkFun_SGP30_Arduino_Library-master/src/SparkFun_SGP30_Arduino_Library.h:144:13: warning: extra qualification 'SGP30::' on member '_CRC8' [-fpermissive]
     uint8_t SGP30::_CRC8(uint16_t twoBytes);

### Expected behaviour
No warnings or errors when compiling the examples

**Comment by nseidle** [comment]
Compiles w/o warnings on uno. Fails on SAMD21. Must be compiler setting related but I did find the bug. We had an extra SGP:: qualifier in the class. Removed and pushed. Should be fixed in the next lib version release (here in a couple minutes). 

Thanks for reporting!
