### ISSUE TITLE
wire.begin() call is wrong here

### ISSUE THREAD

**Issue by coelner** [sparkfun/SparkFun_SGP30_Arduino_Library#7]
https://github.com/sparkfun/SparkFun_SGP30_Arduino_Library/blob/83105b9d7c6a7171540ee068968eb7f6d1b0905f/src/SparkFun_SGP30_Arduino_Library.cpp#L59

https://github.com/sparkfun/SparkFun_CCS811_Arduino_Library/issues/13

**Comment by nseidle** [comment]
Thanks! Fixed in v1.0.4.
